# Site settings
title: Harish Gandhi
description: Harish Gandhi
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Harish gandhi
user_description: Machine Learning & Python Scripting
user_title: Harish gandhi
email: hramachandran@hawk.iit.edu
twitter_username: Harishaaram91
linkedin_username: harish-gandhi
github_username:  harishaaram
instagram_username: harishaaram


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
